# Generated by Django 6.0.5 on 2026-09-11 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="სახელი")),
                ("last_name", models.CharField(max_length=100, verbose_name="გვარი")),
                ("date_of_birth", models.DateField(verbose_name="დაბადების თარიღი")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="თერაპიის დაწყების თარიღი",
                    ),
                ),
                (
                    "session_duration_minutes",
                    models.PositiveIntegerField(
                        default=45, verbose_name="სესიის ხანგრძლივობა (წთ)"
                    ),
                ),
                (
                    "weekly_sessions_planned",
                    models.PositiveIntegerField(
                        default=2, verbose_name="კვირაში დაგეგმილი სესიები"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="დამატებითი მოკლე ინფორმაცია"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="შექმნის დრო"),
                ),
            ],
            options={
                "verbose_name": "ბენეფიციარი",
                "verbose_name_plural": "ბენეფიციარები",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="FunctionalOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="ფუნქციური შედეგი"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
            ],
            options={
                "verbose_name": "ფუნქციური შედეგი",
                "verbose_name_plural": "ფუნქციური შედეგები",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SensoryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="რეაქციის დასახელება"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
            ],
            options={
                "verbose_name": "ბავშვის რეაქცია",
                "verbose_name_plural": "ბავშვის რეაქციები",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SensorySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="დასახელება"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="სლაგი"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ხატულა/სიმბოლო"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="აღწერა")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="თანმიმდევრობა"
                    ),
                ),
            ],
            options={
                "verbose_name": "სენსორული სისტემა",
                "verbose_name_plural": "სენსორული სისტემები",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("sensory_regulation", "სენსორული რეგულაცია"),
                            ("attention", "ყურადღება"),
                            ("fine_motor", "წვრილი მოტორიკა"),
                            ("visual_motor", "ვიზუალურ-მოტორული უნარები"),
                            ("gross_motor", "უხეში მოტორიკა"),
                            ("motor_planning", "მოტორული დაგეგმვა"),
                            ("self_care", "თვითმოვლა"),
                            ("play", "თამაში"),
                            ("transitions", "გადასვლები"),
                            ("functional_participation", "ფუნქციური მონაწილეობა"),
                            ("other", "სხვა"),
                        ],
                        default="sensory_regulation",
                        max_length=50,
                        verbose_name="სფერო",
                    ),
                ),
                ("description", models.TextField(verbose_name="მიზნის აღწერა")),
                (
                    "baseline_state",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="საწყისი მდგომარეობა"
                    ),
                ),
                (
                    "target_state",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="სამიზნე მდგომარეობა"
                    ),
                ),
                (
                    "metric_unit",
                    models.CharField(
                        default="წუთი",
                        help_text="წუთი, რაოდენობა, დახმარების დონე, დამოუკიდებლობის %, სიხშირე და ა.შ.",
                        max_length=100,
                        verbose_name="საზომი ერთეული",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="სამიზნე ვადა"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "აქტიური"),
                            ("achieved", "მიღწეული"),
                            ("modified", "შეცვლილი"),
                            ("discontinued", "შეწყვეტილი"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="შექმნის თარიღი"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="განახლების დრო"),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="core.beneficiary",
                        verbose_name="ბენეფიციარი",
                    ),
                ),
            ],
            options={
                "verbose_name": "თერაპიული მიზანი",
                "verbose_name_plural": "თერაპიული მიზნები",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="წელი")),
                ("month", models.PositiveIntegerField(verbose_name="თვე")),
                (
                    "sessions_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="სესიების რაოდენობა"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ოკუპაციური თერაპიის ყოველთვიური პროგრესის ანგარიში",
                        max_length=255,
                        verbose_name="ანგარიშის სათაური",
                    ),
                ),
                (
                    "section_1_directions",
                    models.TextField(verbose_name="1. თერაპიის ძირითადი მიმართულებები"),
                ),
                (
                    "section_2_goals",
                    models.TextField(verbose_name="2. მიმდინარე მიზნები"),
                ),
                (
                    "section_3_work_performed",
                    models.TextField(verbose_name="3. შესრულებული სამუშაო"),
                ),
                (
                    "section_4_sensory_interventions",
                    models.TextField(
                        verbose_name="4. გამოყენებული სენსორული ინტერვენციები/აქტივობები"
                    ),
                ),
                (
                    "section_5_child_response",
                    models.TextField(verbose_name="5. ბავშვის რეაქცია და ჩართულობა"),
                ),
                (
                    "section_6_quantitative_progress",
                    models.TextField(verbose_name="6. რაოდენობრივი პროგრესი"),
                ),
                (
                    "section_7_functional_changes",
                    models.TextField(verbose_name="7. ფუნქციური ცვლილებები"),
                ),
                (
                    "section_8_challenges",
                    models.TextField(verbose_name="8. არსებული სირთულეები"),
                ),
                (
                    "section_9_recommendations",
                    models.TextField(verbose_name="9. რეკომენდაციები"),
                ),
                (
                    "section_10_next_goals",
                    models.TextField(verbose_name="10. შემდეგი პერიოდის მიზნები"),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False, verbose_name="საბოლოოა / დამტკიცებული"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="შექმნის დრო"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="განახლების დრო"),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="core.beneficiary",
                        verbose_name="ბენეფიციარი",
                    ),
                ),
            ],
            options={
                "verbose_name": "თვის ანგარიში",
                "verbose_name_plural": "თვის ანგარიშები",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="OccupationalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "self_care",
                    models.TextField(
                        blank=True,
                        help_text="ჩაცმა, გახდა, კვება, ჭურჭლის გამოყენება, ხელების დაბანა, კბილების გახეხვა, ტუალეტი, ჰიგიენა",
                        verbose_name="თვითმოვლა",
                    ),
                ),
                (
                    "play",
                    models.TextField(
                        blank=True,
                        help_text="დამოუკიდებელი, ფუნქციური, წარმოსახვითი, დაწყება, გაგრძელება, დასრულება, სხვასთან თამაში",
                        verbose_name="თამაში",
                    ),
                ),
                (
                    "attention",
                    models.TextField(
                        blank=True,
                        help_text="აქტივობის დაწყება, ჩართულობა, შენარჩუნება, დასრულება, ყურადღების გადატანა",
                        verbose_name="ყურადღება",
                    ),
                ),
                (
                    "motor_skills",
                    models.TextField(
                        blank=True,
                        help_text="წვრილი მოტორიკა, ხელისა და თვალის კოორდინაცია, ორმხრივი, მოტორული დაგეგმვა, სხეულის ცნობიერება, ბალანსი",
                        verbose_name="მოტორული სფერო",
                    ),
                ),
                (
                    "functional_participation",
                    models.TextField(
                        blank=True,
                        help_text="სასწავლო აქტივობა, თამაში, თვითმოვლა, სოციალური, გადასვლა აქტივობებს შორის, ყოველდღიური რუტინა",
                        verbose_name="ფუნქციური მონაწილეობა",
                    ),
                ),
                (
                    "general_notes",
                    models.TextField(
                        blank=True, verbose_name="ზოგადი კლინიკური დაკვირვებები"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="განახლების დრო"),
                ),
                (
                    "beneficiary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupational_profile",
                        to="core.beneficiary",
                        verbose_name="ბენეფიციარი",
                    ),
                ),
            ],
            options={
                "verbose_name": "ოკუპაციური პროფილი",
                "verbose_name_plural": "ოკუპაციური პროფილები",
            },
        ),
        migrations.CreateModel(
            name="ReportRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ცვლილების შენიშვნა"
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(default=dict, verbose_name="მონაცემთა სნეპშოტი"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="რევიზიის დრო"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="core.monthlyreport",
                        verbose_name="ანგარიში",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="რედაქტორი",
                    ),
                ),
            ],
            options={
                "verbose_name": "ანგარიშის რევიზია",
                "verbose_name_plural": "ანგარიშის რევიზიები",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensoryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tactile",
                    models.TextField(blank=True, verbose_name="ტაქტილური სისტემა"),
                ),
                (
                    "proprioceptive",
                    models.TextField(blank=True, verbose_name="პროპრიოცეპტული სისტემა"),
                ),
                (
                    "vestibular",
                    models.TextField(blank=True, verbose_name="ვესტიბულარული სისტემა"),
                ),
                (
                    "auditory",
                    models.TextField(blank=True, verbose_name="სმენითი სისტემა"),
                ),
                (
                    "visual",
                    models.TextField(blank=True, verbose_name="მხედველობითი სისტემა"),
                ),
                (
                    "olfactory",
                    models.TextField(blank=True, verbose_name="ყნოსვითი სისტემა"),
                ),
                (
                    "gustatory",
                    models.TextField(blank=True, verbose_name="გემოვნებითი სისტემა"),
                ),
                (
                    "interoceptive",
                    models.TextField(blank=True, verbose_name="ინტერცეპციული სისტემა"),
                ),
                (
                    "multisensory",
                    models.TextField(
                        blank=True, verbose_name="მულტისენსორული თავისებურებები"
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        verbose_name="დამუშავების სტილი და რეგულაციის დაკვირვებები",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="განახლების დრო"),
                ),
                (
                    "beneficiary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensory_profile",
                        to="core.beneficiary",
                        verbose_name="ბენეფიციარი",
                    ),
                ),
            ],
            options={
                "verbose_name": "სენსორული პროფილი",
                "verbose_name_plural": "სენსორული პროფილები",
            },
        ),
        migrations.CreateModel(
            name="SensoryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="აქტივობის დასახელება"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="აღწერა")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
                (
                    "sensory_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.sensorysystem",
                        verbose_name="სენსორული სისტემა",
                    ),
                ),
            ],
            options={
                "verbose_name": "სენსორული აქტივობა",
                "verbose_name_plural": "სენსორული აქტივობები",
                "ordering": ["sensory_system", "name"],
                "unique_together": {("sensory_system", "name")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="სესიის თარიღი"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=45, verbose_name="ხანგრძლივობა (წთ)"
                    ),
                ),
                (
                    "initial_state",
                    models.CharField(
                        choices=[
                            ("calm", "მშვიდი"),
                            ("stable", "სტაბილური"),
                            ("active", "აქტიური"),
                            ("aroused", "აღგზნებული"),
                            ("tense", "დაძაბული"),
                            ("tired", "დაღლილი"),
                            ("low_engagement", "დაბალი ჩართულობა"),
                            ("distress", "დისტრესის ნიშნები"),
                            ("other", "სხვა"),
                        ],
                        default="calm",
                        max_length=30,
                        verbose_name="საწყისი მდგომარეობა",
                    ),
                ),
                (
                    "final_state",
                    models.CharField(
                        choices=[
                            ("calm", "მშვიდი"),
                            ("stable", "სტაბილური"),
                            ("more_engaged", "უფრო ჩართული"),
                            ("less_engaged", "ნაკლებად ჩართული"),
                            ("aroused", "აღგზნებული"),
                            ("tired", "დაღლილი"),
                            ("distress", "დისტრესის ნიშნები"),
                            ("other", "სხვა"),
                        ],
                        default="stable",
                        max_length=30,
                        verbose_name="საბოლოო მდგომარეობა",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="მოკლე პროფესიული ჩანაწერი"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="შექმნის დრო"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="განახლების დრო"),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.beneficiary",
                        verbose_name="ბენეფიციარი",
                    ),
                ),
                (
                    "functional_outcomes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sessions",
                        to="core.functionaloutcome",
                        verbose_name="ფუნქციური შედეგები",
                    ),
                ),
            ],
            options={
                "verbose_name": "სესია",
                "verbose_name_plural": "სესიები",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="მიღწეული მაჩვენებელი"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="შენიშვნა"
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_goals",
                        to="core.goal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_goals",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "სესიის მიზანი",
                "verbose_name_plural": "სესიის მიზნები",
                "unique_together": {("session", "goal")},
            },
        ),
        migrations.AddField(
            model_name="session",
            name="goals",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                through="core.SessionGoal",
                to="core.goal",
                verbose_name="სესიის მიზნები",
            ),
        ),
        migrations.CreateModel(
            name="SessionSensoryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=5, verbose_name="ხანგრძლივობა (წთ)"
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("low", "დაბალი"),
                            ("medium", "საშუალო"),
                            ("high", "მაღალი"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="ინტენსივობა",
                    ),
                ),
                (
                    "repetition_count",
                    models.PositiveIntegerField(default=1, verbose_name="გამეორება"),
                ),
                (
                    "assistance_level",
                    models.CharField(
                        choices=[
                            ("independent", "დამოუკიდებლად"),
                            ("verbal", "სიტყვიერი მითითება"),
                            ("minimal", "მცირე დახმარება"),
                            ("moderate", "საშუალო დახმარება"),
                            ("maximal", "დიდი დახმარება"),
                            ("full", "სრული დახმარება"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="დახმარების დონე",
                    ),
                ),
                (
                    "activity_start",
                    models.CharField(
                        choices=[
                            ("independent", "დამოუკიდებლად დაიწყო"),
                            ("cue", "მითითების შემდეგ"),
                            ("assisted", "დახმარებით"),
                        ],
                        default="cue",
                        max_length=20,
                        verbose_name="აქტივობის დაწყება",
                    ),
                ),
                (
                    "movement_direction",
                    models.CharField(
                        choices=[
                            ("none", "არ გამოიყენება"),
                            ("forward", "წინ"),
                            ("backward", "უკან"),
                            ("left", "მარცხნივ"),
                            ("right", "მარჯვნივ"),
                            ("up", "ზემოთ"),
                            ("down", "ქვემოთ"),
                            ("circular", "წრიული"),
                            ("various", "სხვადასხვა მიმართულება"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="მოძრაობის მიმართულება",
                    ),
                ),
                (
                    "speed",
                    models.CharField(
                        choices=[
                            ("none", "არ გამოიყენება"),
                            ("slow", "ნელი"),
                            ("medium", "საშუალო"),
                            ("fast", "სწრაფი"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="სიჩქარე",
                    ),
                ),
                (
                    "interoception_mode",
                    models.CharField(
                        choices=[
                            ("none", "არ გამოიყენება"),
                            ("self_expressed", "ბავშვმა თვითონ გამოხატა/დაასახელა"),
                            ("observed", "თერაპევტმა დააკვირდა"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="ინტერცეპციის ფიქსაცია",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="შენიშვნა"
                    ),
                ),
                (
                    "responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="session_activities",
                        to="core.sensoryresponse",
                        verbose_name="ბავშვის რეაქციები",
                    ),
                ),
                (
                    "sensory_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_activities",
                        to="core.sensoryactivity",
                        verbose_name="სენსორული აქტივობა",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensory_activities",
                        to="core.session",
                        verbose_name="სესია",
                    ),
                ),
            ],
            options={
                "verbose_name": "სესიის სენსორული აქტივობა",
                "verbose_name_plural": "სესიის სენსორული აქტივობები",
            },
        ),
        migrations.CreateModel(
            name="TherapistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ტელეფონი"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ოკუპაციური თერაპევტი",
                        max_length=150,
                        verbose_name="პროფესიული როლი",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        default="ოკუპაციური თერაპიის ცენტრი",
                        max_length=200,
                        verbose_name="ცენტრი / კლინიკა",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ლიცენზია / სერტიფიკატი",
                    ),
                ),
                (
                    "is_admin_role",
                    models.BooleanField(default=False, verbose_name="ადმინისტრატორი"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "თერაპევტის პროფილი",
                "verbose_name_plural": "თერაპევტების პროფილები",
            },
        ),
        migrations.AddField(
            model_name="session",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="core.therapistprofile",
                verbose_name="თერაპევტი",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_reports",
                to="core.therapistprofile",
                verbose_name="თერაპევტი",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="core.therapistprofile",
                verbose_name="თერაპევტი",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiaries",
                to="core.therapistprofile",
                verbose_name="თერაპევტი",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyreport",
            unique_together={("beneficiary", "year", "month")},
        ),
    ]
