# Generated by Django 6.0.5 on 2026-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="notes",
            field=models.TextField(blank=True, verbose_name="შენიშვნები"),
        ),
        migrations.AddField(
            model_name="goal",
            name="progress_percentage",
            field=models.PositiveIntegerField(default=0, verbose_name="პროგრესის %"),
        ),
        migrations.AddField(
            model_name="sensorysystem",
            name="category",
            field=models.CharField(
                choices=[
                    ("movement", "მოძრაობა და სხეული"),
                    ("tactile_sensory", "შეხება და შეგრძნება"),
                    ("environment", "გარემო და აღქმა"),
                ],
                default="movement",
                max_length=30,
                verbose_name="კატეგორია",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="challenges",
            field=models.JSONField(
                blank=True, default=list, verbose_name="სესიის გამოწვევები (ჩეკბოქსები)"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="session_duration_minutes",
            field=models.PositiveIntegerField(
                default=50, verbose_name="სესიის ხანგრძლივობა (წთ)"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="baseline_state",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="საწყისი მდგომარეობა (Baseline)",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="metric_unit",
            field=models.CharField(
                blank=True,
                default="წუთი",
                help_text="წუთი, რაოდენობა, დახმარების დონე, დამოუკიდებლობის %, სიხშირე და ა.შ.",
                max_length=50,
                verbose_name="საზომი ერთეული",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "აქტიური"),
                    ("achieved", "მიღწეული"),
                    ("modified", "მოდიფიცირებული"),
                    ("on_hold", "შეჩერებული"),
                ],
                default="active",
                max_length=20,
                verbose_name="სტატუსი",
            ),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="auditory",
            field=models.TextField(blank=True, verbose_name="სმენითი"),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="gustatory",
            field=models.TextField(blank=True, verbose_name="გემოვნებითი"),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="interoceptive",
            field=models.TextField(
                blank=True, verbose_name="ინტერცეპციული (შინაგანი ორგანოები)"
            ),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="olfactory",
            field=models.TextField(blank=True, verbose_name="ყნოსვითი"),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="proprioceptive",
            field=models.TextField(
                blank=True, verbose_name="პროპრიოცეპტული (სხეულის შეგრძნება)"
            ),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="tactile",
            field=models.TextField(blank=True, verbose_name="ტაქტილური (შეხება)"),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="vestibular",
            field=models.TextField(
                blank=True, verbose_name="ვესტიბულარული (მოძრაობა და წონასწორობა)"
            ),
        ),
        migrations.AlterField(
            model_name="sensoryprofile",
            name="visual",
            field=models.TextField(blank=True, verbose_name="მხედველობითი"),
        ),
        migrations.AlterField(
            model_name="session",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=50, verbose_name="ხანგრძლივობა (წთ)"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="final_state",
            field=models.CharField(
                choices=[
                    ("blue", "ლურჯი ზონა (დაბალი ენერგია / ჰიპოაქტიური)"),
                    ("green", "მწვანე ზონა (ოპტიმალური / მშვიდი, ფოკუსირებული)"),
                    ("yellow", "ყვითელი ზონა (მომატებული / აღგზნებული)"),
                    ("red", "წითელი ზონა (კრიზისი / დისტრესი)"),
                ],
                default="green",
                max_length=30,
                verbose_name="საბოლოო რეგულაციის ზონა",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="initial_state",
            field=models.CharField(
                choices=[
                    ("blue", "ლურჯი ზონა (დაბალი ენერგია / ჰიპოაქტიური)"),
                    ("green", "მწვანე ზონა (ოპტიმალური / მშვიდი, ფოკუსირებული)"),
                    ("yellow", "ყვითელი ზონა (მომატებული / აღგზნებული)"),
                    ("red", "წითელი ზონა (კრიზისი / დისტრესი)"),
                ],
                default="green",
                max_length=30,
                verbose_name="საწყისი რეგულაციის ზონა",
            ),
        ),
    ]
