# Generated by Django 6.0.5 on 2026-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_goal_notes_goal_progress_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="criteria_type",
            field=models.CharField(
                blank=True,
                default="prompts",
                max_length=50,
                verbose_name="საზომი კრიტერიუმის ტიპი",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="environment_context",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="გარემო და კონტექსტი (E)"
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ოკუპაცია/აქტივობა (O)"
            ),
        ),
    ]
