# Generated by Django 6.0.5 on 2026-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_goal_criteria_type_goal_environment_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="baseline_numeric",
            field=models.FloatField(default=0.0, verbose_name="საწყისი მაჩვენებელი"),
        ),
        migrations.AddField(
            model_name="goal",
            name="current_numeric",
            field=models.FloatField(default=0.0, verbose_name="მიმდინარე მაჩვენებელი"),
        ),
        migrations.AddField(
            model_name="goal",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("percentage", "პროცენტული მაჩვენებელი (0-100%)"),
                    ("duration", "ხანგრძლივობა / დრო (წუთი/წამი)"),
                    ("frequency", "სიხშირე / მცდელობები (რაოდენობა)"),
                    ("prompt_level", "დახმარების დონე (დამოუკიდებლობის კიბე)"),
                ],
                default="percentage",
                max_length=30,
                verbose_name="გაზომვის ტიპი",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="target_numeric",
            field=models.FloatField(default=100.0, verbose_name="სამიზნე მაჩვენებელი"),
        ),
        migrations.AddField(
            model_name="goal",
            name="unit_label",
            field=models.CharField(
                blank=True, default="%", max_length=30, verbose_name="საზომი ერთეული"
            ),
        ),
        migrations.AddField(
            model_name="sessiongoal",
            name="prompt_level",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="დახმარების დონე"
            ),
        ),
        migrations.AddField(
            model_name="sessiongoal",
            name="recorded_numeric",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ფიქსირებული რიცხვითი მაჩვენებელი"
            ),
        ),
        migrations.AlterField(
            model_name="sessiongoal",
            name="progress_value",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="მიღწეული მაჩვენებელი (ტექსტური)",
            ),
        ),
    ]
