# Generated by Django 6.0.5 on 2026-09-17 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_goal_baseline_numeric_goal_current_numeric_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="თარიღი"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="დაწყების დრო")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=50, verbose_name="ხანგრძლივობა (წთ)"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="დასრულების დრო"
                    ),
                ),
                (
                    "therapy_type",
                    models.CharField(
                        default="ოკუპაციური თერაპია",
                        max_length=100,
                        verbose_name="თერაპია",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "დაგეგმილი"),
                            ("completed", "ჩატარდა"),
                            ("missed", "გაცდენა"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="შენიშვნა"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="შექმნის დრო"),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="core.beneficiary",
                        verbose_name="ბენეფიციარი",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_slots",
                        to="core.session",
                        verbose_name="მიბმული სესია",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="core.therapistprofile",
                        verbose_name="თერაპევტი",
                    ),
                ),
            ],
            options={
                "verbose_name": "განრიგის ვიზიტი",
                "verbose_name_plural": "განრიგის ვიზიტები",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
