# Generated by Django 6.0.5 on 2026-09-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_scheduleslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleslot",
            name="series_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="სერიის ID"
            ),
        ),
    ]
